name: React CI Pipeline

on:
    push:
        branches:
            - main # Runs the pipeline on pushes to the main branch
            
    pull_request:
        branches:
            - main # Runs the pipeline when a PR is opened targeting the main branch


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3 # Check out the code from the repository

            - name: Set Up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 22.11.0 # Match your Node.js version with your local setup
            - name: Install Dependencies
              run: npm install
            
            - name: Run Jest Tests
              run: npm run test

            - name: Build Project
              run: npm run build
